MojTermin/MojTermin/MojTermin.Web/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MojTermin.Domain.DomainModels;
using MojTermin.Domain.Identity;
using MojTermin.Service.Interface;
using MojTermin.Web.Data;

namespace MojTermin.Web.Controllers
{
    public class DoctorsController : Controller
    {
        private readonly IDoctorService _doctorService;
        private readonly ISpecialtyService _specialtyService;
        private readonly UserManager<MojTerminUser> _userManager;
        private readonly IRoleService _roleService;
        private readonly IPatientService _patientService;
        private readonly IVisitService _visitService;
        private readonly IReferralService _referralService;

        public DoctorsController(IDoctorService doctorService, ISpecialtyService specialtyService, UserManager<MojTerminUser> userManager, IRoleService roleService, IPatientService patientService, IVisitService visitService, IReferralService referralService)
        {
            _doctorService = doctorService;
            _specialtyService = specialtyService;
            _userManager = userManager;
            _roleService = roleService;
            _patientService = patientService;
            _visitService = visitService;
            _referralService = referralService;
        }

        // GET: Doctors
        public IActionResult Index()
        {
            List<Specialty> specialties = _specialtyService.GetAll().ToList();
            ViewBag.Message = specialties;
            List<Patient> patients = _patientService.GetAllPatients().ToList();
            ViewBag.Patients = patients;
            List<Visit> visits = _visitService.GetAllVisits().ToList();
            ViewBag.Visits = visits;
            List<Referral> referrals = _referralService.GetAllReferrals().ToList();
            ViewBag.Referrals = referrals;

            List<Role> roles = _roleService.GetAllRoles().ToList();
            var userId = _userManager.GetUserId(HttpContext.User);

            MojTerminUser user = _userManager.FindByIdAsync(userId).Result;
            if (user != null)
            {
                string role = user.Role.Name;
                ViewBag.Message1 = role;
            }
            return View(this._doctorService.GetAllDoctors());
        }

        // GET: Doctors/Create
        public IActionResult Create()
        {
            List<Specialty> specialties = _specialtyService.GetAll().ToList();
            ViewBag.Message = specialties;
            return View();
        }

       
        // GET: Doctors/Details/5
        public IActionResult Details(Guid? id)
        {
            List<Specialty> specialties = _specialtyService.GetAll().ToList();
            ViewBag.Message = specialties;
            if (id == null)
            {
                return NotFound();
            }

            var doctor = this._doctorService.Get((Guid) id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // POST: Doctors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Ssn,Name,Surname,LicenceNumber,Specialty")] Doctor doctor, IFormCollection formCollection)
        {
            if (ModelState.IsValid)
            {
                doctor.Id = Guid.NewGuid();
                Guid specialtyId = Guid.Parse(formCollection["Specialty"]);
                Specialty specialty = _specialtyService.Get(specialtyId);
                doctor.Specialty = specialty;
                this._doctorService.CreateNewDoctor(doctor);
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }

        // GET: Doctors/Edit/5
        public IActionResult Edit(Guid? id)
        {
            List<Specialty> specialties = _specialtyService.GetAll().ToList();
            ViewBag.Message = specialties;
            if (id == null)
            {
                return NotFound();
            }

            var doctor = this._doctorService.Get((Guid)id);
            if (doctor == null)
            {
                return NotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid? id, [Bind("Id,Ssn,Name,Surname,LicenceNumber,Specialty")] Doctor doctor, IFormCollection formCollection)
        {
            List<Specialty> specialties = _specialtyService.GetAll().ToList();
            ViewBag.Message = specialties;
            if (id != doctor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Guid specialtyId = Guid.Parse(formCollection["Specialty"]);
                    Specialty specialty = _specialtyService.Get(specialtyId);
                    doctor.Specialty = specialty;
                    this._doctorService.UpdateDoctor(doctor);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorExists(doctor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = this._doctorService.Get((Guid)id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            this._doctorService.DeleteDoctor(id);
            return RedirectToAction(nameof(Index));
        }


        private bool DoctorExists(Guid id)
        {
            return this._doctorService.Get(id) != null;
        }


    }
}

MojTermin/MojTermin/MojTermin.Web/Views/Doctors/Create.cshtml
@using MojTermin.Domain.DomainModels;
@model MojTermin.Domain.DomainModels.Doctor;
@{
    ViewData["Title"] = "Create";

}

@{
    var data = ViewBag.Message;
}

<h1>Create</h1>

<h4>Doctor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Create", "Doctors", FormMethod.Post))
        {
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Ssn" class="control-label"></label>
                    <input asp-for="Ssn" class="form-control" />
                    <span asp-validation-for="Ssn" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Surname" class="control-label"></label>
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LicenceNumber" class="control-label"></label>
                    <input asp-for="LicenceNumber" class="form-control" />
                    <span asp-validation-for="LicenceNumber" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Specialty" class="control-label"></label>

                    <select name="Specialty" id="Specialty" class="form-control">
                        <option selected value="0">Select</option>
                        @foreach (Specialty specialty in (List<Specialty>)ViewBag.Message)
                        {
                            <option value="@specialty.Id"> @specialty.Name</option>
                        }
                    </select>
                </div>
                    
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>   
                    
                
        }
            </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MojTermin/MojTermin/MojTermin.Web/Views/Doctors/Delete.cshtml
@model MojTermin.Domain.DomainModels.Doctor

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ssn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ssn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LicenceNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LicenceNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MojTermin/MojTermin/MojTermin.Web/Views/Doctors/Details.cshtml
@model MojTermin.Domain.DomainModels.Doctor

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ssn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ssn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LicenceNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LicenceNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Specialty)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Specialty.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MojTermin/MojTermin/MojTermin.Web/Views/Doctors/Edit.cshtml
@model MojTermin.Domain.DomainModels.Doctor
@using MojTermin.Domain.DomainModels;
@{
    ViewData["Title"] = "Edit";
}
@{
    var data = ViewBag.Message;
}
<h1>Edit</h1>

<h4>Doctor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Edit", "Doctors", FormMethod.Post))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ssn" class="control-label"></label>
                <input asp-for="Ssn" class="form-control" />
                <span asp-validation-for="Ssn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LicenceNumber" class="control-label"></label>
                <input asp-for="LicenceNumber" class="form-control" />
                <span asp-validation-for="LicenceNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Specialty" class="control-label"></label>
                <select name="Specialty" id="Specialty" class="form-control">
                    <option selected value="@Model.Specialty.Id"> @Model.Specialty.Name</option>
                    @foreach (Specialty specialty in (List<Specialty>)ViewBag.Message)
                    {
                        if (specialty.Id != Model.Specialty.Id)
                        {
                            <option value="@specialty.Id"> @specialty.Name</option>
                        }

                    }
                 </select>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MojTermin/MojTermin/MojTermin.Web/Views/Doctors/Index.cshtml
@model IEnumerable<MojTermin.Domain.DomainModels.Doctor>
@using MojTermin.Domain.DomainModels;

@{
    ViewData["Title"] = "Index";
}
@{
    var patients = (List<Patient>)ViewBag.Patients;
    var visits = (List<Visit>)ViewBag.Visits;
    var referrals = (List<Referral>)ViewBag.Referrals;
}
<h1>Doctors</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Ssn</th>
            <th>Name</th>
            <th>Surname</th>
            <th>LicenceNumber</th>
            <th>Specialty</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var doctor in Model)
        {
            <tr>
                <td>@doctor.Ssn</td>
                <td>@doctor.Name</td>
                <td>@doctor.Surname</td>
                <td>@doctor.LicenceNumber</td>
                <td>@doctor.Specialty.Name</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@doctor.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@doctor.Id">Details</a> |
                    @if (!patients.Any(patient => patient.Doctor.Id == doctor.Id)
                        && !visits.Any(visit => visit.Doctor.Id == doctor.Id) && 
                        !referrals.Any(referral => referral.ForwardTo.Id == doctor.Id))
                    {
                        <a asp-action="Delete" asp-route-id="@doctor.Id">Delete</a>
                    }
                        
                </td>
            </tr>
        }
    </tbody>
</table>