MojTermin/MojTermin/MojTermin.Web/Controllers/VisitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MojTermin.Domain.DomainModels;
using MojTermin.Domain.Identity;
using MojTermin.Service.Interface;
using MojTermin.Web.Data;

namespace MojTermin.Web.Controllers
{
    public class VisitsController : Controller
    {
        private readonly IVisitService _visitService;
        private readonly IDoctorService _doctorService;
        private readonly IPatientService _patientService;
        private readonly UserManager<MojTerminUser> _userManager;
        private readonly IRoleService _roleService;
        private readonly IDiagnosisService _diagnosisService;

        public VisitsController(IVisitService visitService, IDoctorService doctorService, IPatientService patientService, UserManager<MojTerminUser> userManager, IRoleService roleService, IDiagnosisService diagnosisService)
        {
            _visitService = visitService;
            _doctorService = doctorService;
            _patientService = patientService;
            _userManager = userManager;
            _roleService = roleService;
            _diagnosisService = diagnosisService;
        }

        // GET: Visits
        public IActionResult Index()
        {
            List<Doctor> doctors = _doctorService.GetAllDoctors().ToList();
            ViewBag.Doctors = doctors;
            List<Patient> patients = _patientService.GetAllPatients().ToList();
            ViewBag.Patients = patients;
            List<Diagnosis> diagnoses = _diagnosisService.GetAllDiagnoses().ToList();
            ViewBag.Diagnoses = diagnoses;

            List<Role> roles = _roleService.GetAllRoles().ToList();
            var userId = _userManager.GetUserId(HttpContext.User);

            MojTerminUser user = _userManager.FindByIdAsync(userId).Result;
            if (user != null)
            {
                string role = user.Role.Name;
                ViewBag.Message1 = role;
            }
            return View(this._visitService.GetAllVisits());
        }

        // GET: Visits/Details/5
        public IActionResult Details(Guid? id)
        {
            List<Doctor> doctors = _doctorService.GetAllDoctors().ToList();
            ViewBag.Doctors = doctors;
            List<Patient> patients = _patientService.GetAllPatients().ToList();
            ViewBag.Patients = patients;
            if (id == null)
            {
                return NotFound();
            }

            var visit = this._visitService.Get((Guid)id);
            if (visit == null)
            {
                return NotFound();
            }

            return View(visit);
        }

        // GET: Visits/Create
        public IActionResult Create()
        {
            List<Doctor> doctors = _doctorService.GetAllDoctors().ToList();
            ViewBag.Doctors = doctors;
            List<Patient> patients = _patientService.GetAllPatients().ToList();
            ViewBag.Patients = patients;
            return View();
        }

        // POST: Visits/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Term,Id,Patient,Doctor")] Visit visit, IFormCollection formCollection)
        {
            if (ModelState.IsValid)
            {
                visit.Id = Guid.NewGuid();

                Guid patientId = Guid.Parse(formCollection["Patient"]);
                Patient patient = _patientService.Get(patientId);
                visit.Patient = patient;

                Guid doctorId = Guid.Parse(formCollection["Doctor"]);
                Doctor doctor = _doctorService.Get(doctorId);
                visit.Doctor = doctor;

                string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                this._visitService.CreateNewVisit(visit, userId);
                return RedirectToAction(nameof(Index));
            }
            return View(visit);
        }

        // GET: Visits/Edit/5
        public IActionResult Edit(Guid? id)
        {
            List<Doctor> doctors = _doctorService.GetAllDoctors().ToList();
            ViewBag.Doctors = doctors;
            List<Patient> patients = _patientService.GetAllPatients().ToList();
            ViewBag.Patients = patients;
            if (id == null)
            {
                return NotFound();
            }

            var visit = this._visitService.Get((Guid)id);
            if (visit == null)
            {
                return NotFound();
            }
            return View(visit);
        }

        // POST: Visits/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, [Bind("Term,Id,Patient,Doctor")] Visit visit, IFormCollection formCollection)
        {
            List<Doctor> doctors = _doctorService.GetAllDoctors().ToList();
            ViewBag.Doctors = doctors;
            List<Patient> patients = _patientService.GetAllPatients().ToList();
            ViewBag.Patients = patients;
            if (id != visit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Guid patientId = Guid.Parse(formCollection["Patient"]);
                    Patient patient = _patientService.Get(patientId);
                    visit.Patient = patient;

                    Guid doctorId = Guid.Parse(formCollection["Doctor"]);
                    Doctor doctor = _doctorService.Get(doctorId);
                    visit.Doctor = doctor;

                    this._visitService.UpdateVisit(visit);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VisitExists(visit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(visit);
        }

        // GET: Visits/Delete/5
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visit = this._visitService.Get((Guid)id);
            if (visit == null)
            {
                return NotFound();
            }

            return View(visit);
        }

        // POST: Visits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            this._visitService.DeleteVisit(id);
            return RedirectToAction(nameof(Index));
        }

        private bool VisitExists(Guid id)
        {
            return this._visitService.Get(id) != null; 
        }
    }
}

MojTermin/MojTermin/MojTermin.Web/Views/Visits/Create.cshtml
@model MojTermin.Domain.DomainModels.Visit
@using MojTermin.Domain.DomainModels;
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Visit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Create", "Visits", FormMethod.Post))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Term" class="control-label"></label>
                <input asp-for="Term" class="form-control" />
                <span asp-validation-for="Term" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Doctor" class="control-label"></label>
                <select name="Doctor" id="Doctor" class="form-control">
                    <option value="0">Select</option>
                    @foreach (Doctor doctor in (List<Doctor>)ViewBag.Doctors)
                    {
                        <option value="@doctor.Id"> @doctor.Name @doctor.Surname</option>
                    }
                </select>
            </div>

            <div class="form-group">
                <label asp-for="Patient" class="control-label"></label>
                <select name="Patient" id="Patient" class="form-control">
                    <option value="0">Select</option>
                    @foreach (Patient patient in (List<Patient>)ViewBag.Patients)
                    {
                        <option value="@patient.Id"> @patient.Name @patient.Surname</option>
                    }
                </select>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        }
        </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MojTermin/MojTermin/MojTermin.Web/Views/Visits/Delete.cshtml
@model MojTermin.Domain.DomainModels.Visit

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Visit</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Term)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Term)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MojTermin/MojTermin/MojTermin.Web/Views/Visits/Details.cshtml
@model MojTermin.Domain.DomainModels.Visit

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Visit</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Term)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Term)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient)
        </dt>
        <dd class="col-sm-10">
            @{
                var patientName = Model.Patient.Name + " " + Model.Patient.Surname;
                @Html.DisplayFor(model => patientName)
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Doctor)
        </dt>
        <dd class="col-sm-10">
            @{
                var doctorName = Model.Doctor.Name + " " + Model.Doctor.Surname;
                @Html.DisplayFor(model => doctorName)
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MojTermin/MojTermin/MojTermin.Web/Views/Visits/Edit.cshtml
@model MojTermin.Domain.DomainModels.Visit
@using MojTermin.Domain.DomainModels;
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Visit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Edit", "Visits", FormMethod.Post))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Term" class="control-label"></label>
                <input asp-for="Term" class="form-control" />
                <span asp-validation-for="Term" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Doctor" class="control-label"></label>
                <select name="Doctor" id="Doctor" class="form-control">
                    <option selected value="@Model.Doctor.Id"> @Model.Doctor.Name @Model.Doctor.Surname</option>
                    @foreach (Doctor doctor in (List<Doctor>)ViewBag.Doctors)
                    {
                        if (doctor.Id != Model.Doctor.Id)
                        {
                            <option value="@doctor.Id"> @doctor.Name @doctor.Surname</option>
                        }
                    }
                </select>
            </div>

            <div class="form-group">
                <label asp-for="Patient" class="control-label"></label>
                <select name="Patient" id="Patient" class="form-control">
                    <option selected value="@Model.Patient.Id"> @Model.Patient.Name @Model.Patient.Surname</option>
                    @foreach (Patient patient in (List<Patient>)ViewBag.Patients)
                    {
                        if (patient.Id != Model.Patient.Id)
                        {
                            <option value="@patient.Id"> @patient.Name @patient.Surname</option>
                        }
                    }
                </select>
            </div>

            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MojTermin/MojTermin/MojTermin.Web/Views/Visits/Index.cshtml
@model IEnumerable<MojTermin.Domain.DomainModels.Visit>
@using MojTermin.Domain.DomainModels;

@{
    ViewData["Title"] = "Index";
}
@{
    var patients = (List<Patient>)ViewBag.Patients;
    var doctors = (List<Doctor>)ViewBag.Doctors;
    var diagnoses = (List<Diagnosis>)ViewBag.Diagnoses;
}

<h1>Visits</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Term</th>
            <th>Patient</th>
            <th>Doctor</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Diagnosis d in diagnoses)
        {
            @foreach (var visit in Model)
            {
                <tr>
                    <td>@visit.Term</td>
                    @{
                        var patientName = visit.Patient.Name + " " + visit.Patient.Surname;
                        <td>@patientName</td>
                    }
                    @{
                        var doctorName = visit.Doctor.Name + " " + visit.Doctor.Surname;
                        <td>@doctorName</td>
                    }
                    <td>
                        <a asp-action="Edit" asp-route-id="@visit.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@visit.Id">Details</a> |

                        @if(!d.Visits.Any(v => v.VisitId == visit.Id))
                        {
                            <a asp-action="Delete" asp-route-id="@visit.Id">Delete</a>
                        }

                    </td>
                </tr>
            }
        }
    </tbody>
</table>